FROM python:3.11-slim

WORKDIR /backend

COPY ./backend /backend

RUN pip install --upgrade pip \
    && pip install -r requirements.txt \
    && pip install pika

ENV PYTHONUNBUFFERED=1

CMD ["python", "manage.py", "consume_notifications"]
