# Generated by Django 5.0.2 on 2025-10-06 15:38

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_doc', models.FileField(blank=True, null=True, upload_to='media/files/% Y/% m/% d/')),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=700, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='media/lessonVideos/% Y/% m/% d/')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_instructor', to='profile_app.profile')),
                ('articles', models.ManyToManyField(blank=True, related_name='lessons_articles', to='course_app.resource')),
                ('links', models.ManyToManyField(blank=True, related_name='lessons_links', to='course_app.resource')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=800, null=True)),
                ('lessons_related', models.ManyToManyField(related_name='courses_lesson', to='course_app.lesson')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_organization', to='course_app.organization')),
            ],
        ),
    ]
