# Generated by Django 5.0.2 on 2025-10-07 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=800, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('course_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='course_app.course')),
                ('students', models.ManyToManyField(blank=True, related_name='terms', to='profile_app.profile')),
            ],
        ),
    ]
