# Generated by Django 5.0.2 on 2025-10-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_alter_resource_file_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file_doc',
            field=models.FileField(blank=True, null=True, upload_to='media/files/% Y/% m/% d/'),
        ),
    ]
