# Generated by Django 5.0.2 on 2025-10-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0006_alter_resource_file_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='enroll_finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='enroll_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
