# Generated by Django 5.0.2 on 2025-11-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0007_term_enroll_finish_date_term_enroll_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_online',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
