# Generated by Django 5.0.2 on 2025-12-07 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0008_course_is_online'),
        ('profile_app', '0006_profileofflinecourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_course', to='course_app.course')),
                ('profile_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_profile', to='profile_app.profile')),
            ],
        ),
    ]
