# Generated by Django 5.0.2 on 2025-12-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0009_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rate',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
