# Generated by Django 5.0.2 on 2025-12-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0010_rating_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True),
        ),
    ]
