# Generated by Django 5.0.2 on 2025-12-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0003_comment_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rate',
        ),
    ]
