# Generated by Django 5.0.2 on 2025-11-13 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_alter_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
