# Generated by Django 5.0.2 on 2025-11-29 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_instructor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='InstructorProfileDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_field', models.CharField(blank=True, max_length=1000, null=True)),
                ('website', models.CharField(blank=True, max_length=1000, null=True)),
                ('work_experience', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='media/files/resume/%Y/%m/%d/')),
                ('about', models.TextField(blank=True, null=True)),
                ('profile_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_InstructorProfileDetail', to='profile_app.profile')),
            ],
        ),
    ]
