# Generated by Django 5.0.2 on 2025-12-01 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0008_course_is_online'),
        ('profile_app', '0005_profile_is_instructor_instructorprofiledetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileOfflineCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offline_course', models.ManyToManyField(blank=True, null=True, related_name='profileOfflineCourses', to='course_app.course')),
                ('profile_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_offlinecourses', to='profile_app.profile')),
            ],
        ),
    ]
