# Generated by Django 5.0.2 on 2025-12-11 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0010_rating_rate'),
        ('profile_app', '0006_profileofflinecourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_course', models.ManyToManyField(blank=True, null=True, related_name='profileAllCourses', to='course_app.course')),
                ('profile_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_detail', to='profile_app.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='ProfileOfflineCourse',
        ),
    ]
