# Generated by Django 5.0.2 on 2025-12-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0007_profiledetail_delete_profileofflinecourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetail',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiledetail',
            name='social_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
